#!/bin/bash

echo "Testing POST /api/timeline_post..."
RESPONSE=$(curl -s -X POST http://127.0.0.1:5000/api/timeline_post \
    -d "name=Automated Test&email=test@example.com&content=This is a random test post generated by a script.")

echo "POST Response:"
echo $RESPONSE

# Extract the ID from the JSON using python to avoid jq dependency
POST_ID=$(echo $RESPONSE | python3 -c "import sys, json; print(json.load(sys.stdin).get('id', ''))")

echo ""
echo "---------------------------------"
echo "Testing GET /api/timeline_post..."
curl -s http://127.0.0.1:5000/api/timeline_post
echo ""

if [ -n "$POST_ID" ]; then
    echo ""
    echo "---------------------------------"
    echo "Testing DELETE /api/timeline_post/$POST_ID..."
    curl -s -X DELETE http://127.0.0.1:5000/api/timeline_post/$POST_ID
    echo -e "\nDeleted post with ID $POST_ID."
else
    echo "Could not extract POST_ID to delete."
fi
